### ISSUE TITLE
什么时候我们才能够说一个陈述是“显然的”？ | hozen.site

### ISSUE THREAD

**Issue by hooozen** [hooozen/hooozen.github.io#79]
https://www.hozen.site/archives/62/ 

 开发者，数理知识和文学创作

**Comment by AlexStark-cn** [comment]
我想知道您是怎么把图片居中的？

**Comment by hooozen** [comment]
@AlexStark-cn 

在我使用的博客主题[hexo-theme-tranquility](https://github.com/hooozen/hexo-theme-tranquility)中，图片的样式是默认居中的。

在该主题中，设置了以下 CSS 样式使图片居中：
```css
p img, figure img {
  display: block;
  margin: 0 auto;
  max-width: 100%;
}
```
